// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AdminStatsPublic
 */
export type AdminStatsPublic = {
    /**
     * Total Cars
     */
    total_cars: number;
    /**
     * Available Cars
     */
    available_cars: number;
    /**
     * Sold Cars
     */
    sold_cars: number;
    /**
     * Featured Cars
     */
    featured_cars: number;
    /**
     * Total Users
     */
    total_users: number;
    /**
     * Total Inquiries
     */
    total_inquiries: number;
    /**
     * New Inquiries
     */
    new_inquiries: number;
};

/**
 * Body_admin-admin_upload_car_images
 */
export type Body_admin_admin_upload_car_images = {
    /**
     * Files
     */
    files: Array<Blob | File>;
};

/**
 * Body_cars-upload_car_images
 */
export type Body_cars_upload_car_images = {
    /**
     * Files
     */
    files: Array<Blob | File>;
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * CarCreate
 */
export type CarCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Make
     */
    make: string;
    /**
     * Model
     */
    model: string;
    /**
     * Year
     */
    year: number;
    /**
     * Price
     */
    price: number;
    /**
     * Mileage
     */
    mileage?: number;
    /**
     * Engine
     */
    engine?: string | null;
    /**
     * Transmission
     */
    transmission?: string | null;
    /**
     * Exterior Color
     */
    exterior_color?: string | null;
    /**
     * Interior Color
     */
    interior_color?: string | null;
    /**
     * Vin
     */
    vin?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Featured
     */
    is_featured?: boolean;
    /**
     * Is Sold
     */
    is_sold?: boolean;
};

/**
 * CarImagePublic
 */
export type CarImagePublic = {
    /**
     * Image Url
     */
    image_url: string;
    /**
     * Is Primary
     */
    is_primary?: boolean;
    /**
     * Display Order
     */
    display_order?: number;
    /**
     * Id
     */
    id: string;
    /**
     * Car Id
     */
    car_id: string;
};

/**
 * CarImageReorder
 */
export type CarImageReorder = {
    /**
     * Image Ids
     */
    image_ids: Array<string>;
};

/**
 * CarInquiriesPublic
 */
export type CarInquiriesPublic = {
    /**
     * Data
     */
    data: Array<CarInquiryPublic>;
    /**
     * Count
     */
    count: number;
    /**
     * New Count
     */
    new_count: number;
};

/**
 * CarInquiryCarPublic
 */
export type CarInquiryCarPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Make
     */
    make: string;
    /**
     * Model
     */
    model: string;
    /**
     * Year
     */
    year: number;
};

/**
 * CarInquiryCreate
 */
export type CarInquiryCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Message
     */
    message?: string | null;
};

/**
 * CarInquiryPublic
 */
export type CarInquiryPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Message
     */
    message?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Car Id
     */
    car_id: string;
    /**
     * Is Read
     */
    is_read: boolean;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Created At
     */
    created_at: string;
    car?: CarInquiryCarPublic | null;
};

/**
 * CarInquiryUpdate
 */
export type CarInquiryUpdate = {
    /**
     * Is Read
     */
    is_read?: boolean | null;
    /**
     * Notes
     */
    notes?: string | null;
};

/**
 * CarPublic
 */
export type CarPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Make
     */
    make: string;
    /**
     * Model
     */
    model: string;
    /**
     * Year
     */
    year: number;
    /**
     * Price
     */
    price: number;
    /**
     * Mileage
     */
    mileage?: number;
    /**
     * Engine
     */
    engine?: string | null;
    /**
     * Transmission
     */
    transmission?: string | null;
    /**
     * Exterior Color
     */
    exterior_color?: string | null;
    /**
     * Interior Color
     */
    interior_color?: string | null;
    /**
     * Vin
     */
    vin?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Featured
     */
    is_featured?: boolean;
    /**
     * Is Sold
     */
    is_sold?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Created By Id
     */
    created_by_id: string;
    created_by?: UserPublic | null;
    /**
     * Images
     */
    images?: Array<CarImagePublic>;
};

/**
 * CarUpdate
 */
export type CarUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Make
     */
    make?: string | null;
    /**
     * Model
     */
    model?: string | null;
    /**
     * Year
     */
    year?: number | null;
    /**
     * Price
     */
    price?: number | null;
    /**
     * Mileage
     */
    mileage?: number | null;
    /**
     * Engine
     */
    engine?: string | null;
    /**
     * Transmission
     */
    transmission?: string | null;
    /**
     * Exterior Color
     */
    exterior_color?: string | null;
    /**
     * Interior Color
     */
    interior_color?: string | null;
    /**
     * Vin
     */
    vin?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Featured
     */
    is_featured?: boolean | null;
    /**
     * Is Sold
     */
    is_sold?: boolean | null;
};

/**
 * CarsPublic
 */
export type CarsPublic = {
    /**
     * Data
     */
    data: Array<CarPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemsPublic
 */
export type ItemsPublic = {
    /**
     * Data
     */
    data: Array<ItemPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * SiteSettingsPublic
 */
export type SiteSettingsPublic = {
    /**
     * Dealership Name
     */
    dealership_name?: string | null;
    /**
     * Hero Headline
     */
    hero_headline?: string | null;
    /**
     * Hero Subheadline
     */
    hero_subheadline?: string | null;
    /**
     * Hero Image Url
     */
    hero_image_url?: string | null;
    /**
     * Hero Video Url
     */
    hero_video_url?: string | null;
    /**
     * Contact Email
     */
    contact_email?: string | null;
    /**
     * Contact Phone
     */
    contact_phone?: string | null;
    /**
     * Address
     */
    address?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * SiteSettingsUpdate
 */
export type SiteSettingsUpdate = {
    /**
     * Dealership Name
     */
    dealership_name?: string | null;
    /**
     * Hero Headline
     */
    hero_headline?: string | null;
    /**
     * Hero Subheadline
     */
    hero_subheadline?: string | null;
    /**
     * Hero Image Url
     */
    hero_image_url?: string | null;
    /**
     * Hero Video Url
     */
    hero_video_url?: string | null;
    /**
     * Contact Email
     */
    contact_email?: string | null;
    /**
     * Contact Phone
     */
    contact_phone?: string | null;
    /**
     * Address
     */
    address?: string | null;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type loginRecoverPasswordHtmlContentResponse = loginRecoverPasswordHtmlContentResponses[keyof loginRecoverPasswordHtmlContentResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type itemsReadItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/items/';
};

export type itemsReadItemsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemsError = itemsReadItemsErrors[keyof itemsReadItemsErrors];

export type itemsReadItemsResponses = {
    /**
     * Successful Response
     */
    200: ItemsPublic;
};

export type itemsReadItemsResponse = itemsReadItemsResponses[keyof itemsReadItemsResponses];

export type itemsCreateItemData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items/';
};

export type itemsCreateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsCreateItemError = itemsCreateItemErrors[keyof itemsCreateItemErrors];

export type itemsCreateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsCreateItemResponse = itemsCreateItemResponses[keyof itemsCreateItemResponses];

export type itemsDeleteItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsDeleteItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsDeleteItemError = itemsDeleteItemErrors[keyof itemsDeleteItemErrors];

export type itemsDeleteItemResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type itemsDeleteItemResponse = itemsDeleteItemResponses[keyof itemsDeleteItemResponses];

export type itemsReadItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsReadItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemError = itemsReadItemErrors[keyof itemsReadItemErrors];

export type itemsReadItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsReadItemResponse = itemsReadItemResponses[keyof itemsReadItemResponses];

export type itemsUpdateItemData = {
    body: ItemUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsUpdateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsUpdateItemError = itemsUpdateItemErrors[keyof itemsUpdateItemErrors];

export type itemsUpdateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsUpdateItemResponse = itemsUpdateItemResponses[keyof itemsUpdateItemResponses];

export type carsReadMakesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/cars/makes';
};

export type carsReadMakesResponses = {
    /**
     * Response Cars-Read Makes
     *
     * Successful Response
     */
    200: Array<string>;
};

export type carsReadMakesResponse = carsReadMakesResponses[keyof carsReadMakesResponses];

export type carsReadCarsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Make
         */
        make?: string | null;
        /**
         * Min Price
         */
        min_price?: number | null;
        /**
         * Max Price
         */
        max_price?: number | null;
        /**
         * Year
         */
        year?: number | null;
        /**
         * Is Featured
         */
        is_featured?: boolean | null;
        /**
         * Include Sold
         */
        include_sold?: boolean;
        /**
         * Search
         */
        search?: string | null;
        /**
         * Sort
         */
        sort?: 'newest' | 'oldest' | 'price_asc' | 'price_desc' | 'year_desc' | 'year_asc' | 'mileage_asc';
    };
    url: '/api/v1/cars/';
};

export type carsReadCarsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type carsReadCarsError = carsReadCarsErrors[keyof carsReadCarsErrors];

export type carsReadCarsResponses = {
    /**
     * Successful Response
     */
    200: CarsPublic;
};

export type carsReadCarsResponse = carsReadCarsResponses[keyof carsReadCarsResponses];

export type carsCreateCarData = {
    body: CarCreate;
    path?: never;
    query?: never;
    url: '/api/v1/cars/';
};

export type carsCreateCarErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type carsCreateCarError = carsCreateCarErrors[keyof carsCreateCarErrors];

export type carsCreateCarResponses = {
    /**
     * Successful Response
     */
    200: CarPublic;
};

export type carsCreateCarResponse = carsCreateCarResponses[keyof carsCreateCarResponses];

export type carsDeleteCarData = {
    body?: never;
    path: {
        /**
         * Car Id
         */
        car_id: string;
    };
    query?: never;
    url: '/api/v1/cars/{car_id}';
};

export type carsDeleteCarErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type carsDeleteCarError = carsDeleteCarErrors[keyof carsDeleteCarErrors];

export type carsDeleteCarResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type carsDeleteCarResponse = carsDeleteCarResponses[keyof carsDeleteCarResponses];

export type carsReadCarData = {
    body?: never;
    path: {
        /**
         * Car Id
         */
        car_id: string;
    };
    query?: never;
    url: '/api/v1/cars/{car_id}';
};

export type carsReadCarErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type carsReadCarError = carsReadCarErrors[keyof carsReadCarErrors];

export type carsReadCarResponses = {
    /**
     * Successful Response
     */
    200: CarPublic;
};

export type carsReadCarResponse = carsReadCarResponses[keyof carsReadCarResponses];

export type carsUpdateCarData = {
    body: CarUpdate;
    path: {
        /**
         * Car Id
         */
        car_id: string;
    };
    query?: never;
    url: '/api/v1/cars/{car_id}';
};

export type carsUpdateCarErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type carsUpdateCarError = carsUpdateCarErrors[keyof carsUpdateCarErrors];

export type carsUpdateCarResponses = {
    /**
     * Successful Response
     */
    200: CarPublic;
};

export type carsUpdateCarResponse = carsUpdateCarResponses[keyof carsUpdateCarResponses];

export type carsUploadCarImagesData = {
    body: Body_cars_upload_car_images;
    path: {
        /**
         * Car Id
         */
        car_id: string;
    };
    query?: never;
    url: '/api/v1/cars/{car_id}/images';
};

export type carsUploadCarImagesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type carsUploadCarImagesError = carsUploadCarImagesErrors[keyof carsUploadCarImagesErrors];

export type carsUploadCarImagesResponses = {
    /**
     * Response Cars-Upload Car Images
     *
     * Successful Response
     */
    200: Array<CarImagePublic>;
};

export type carsUploadCarImagesResponse = carsUploadCarImagesResponses[keyof carsUploadCarImagesResponses];

export type carsDeleteCarImageData = {
    body?: never;
    path: {
        /**
         * Car Id
         */
        car_id: string;
        /**
         * Image Id
         */
        image_id: string;
    };
    query?: never;
    url: '/api/v1/cars/{car_id}/images/{image_id}';
};

export type carsDeleteCarImageErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type carsDeleteCarImageError = carsDeleteCarImageErrors[keyof carsDeleteCarImageErrors];

export type carsDeleteCarImageResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type carsDeleteCarImageResponse = carsDeleteCarImageResponses[keyof carsDeleteCarImageResponses];

export type carsCreateInquiryData = {
    body: CarInquiryCreate;
    path: {
        /**
         * Car Id
         */
        car_id: string;
    };
    query?: never;
    url: '/api/v1/cars/{car_id}/inquiries';
};

export type carsCreateInquiryErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type carsCreateInquiryError = carsCreateInquiryErrors[keyof carsCreateInquiryErrors];

export type carsCreateInquiryResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type carsCreateInquiryResponse = carsCreateInquiryResponses[keyof carsCreateInquiryResponses];

export type adminReadAllCarsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Make
         */
        make?: string | null;
        /**
         * Min Price
         */
        min_price?: number | null;
        /**
         * Max Price
         */
        max_price?: number | null;
        /**
         * Year
         */
        year?: number | null;
        /**
         * Is Featured
         */
        is_featured?: boolean | null;
        /**
         * Is Sold
         */
        is_sold?: boolean | null;
        /**
         * Created By Id
         */
        created_by_id?: string | null;
        /**
         * Search
         */
        search?: string | null;
        /**
         * Sort
         */
        sort?: 'newest' | 'oldest' | 'price_asc' | 'price_desc' | 'year_desc' | 'year_asc' | 'mileage_asc';
    };
    url: '/api/v1/admin/cars/';
};

export type adminReadAllCarsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminReadAllCarsError = adminReadAllCarsErrors[keyof adminReadAllCarsErrors];

export type adminReadAllCarsResponses = {
    /**
     * Successful Response
     */
    200: CarsPublic;
};

export type adminReadAllCarsResponse = adminReadAllCarsResponses[keyof adminReadAllCarsResponses];

export type adminAdminDeleteCarData = {
    body?: never;
    path: {
        /**
         * Car Id
         */
        car_id: string;
    };
    query?: never;
    url: '/api/v1/admin/cars/{car_id}';
};

export type adminAdminDeleteCarErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminAdminDeleteCarError = adminAdminDeleteCarErrors[keyof adminAdminDeleteCarErrors];

export type adminAdminDeleteCarResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type adminAdminDeleteCarResponse = adminAdminDeleteCarResponses[keyof adminAdminDeleteCarResponses];

export type adminAdminUpdateCarData = {
    body: CarUpdate;
    path: {
        /**
         * Car Id
         */
        car_id: string;
    };
    query?: never;
    url: '/api/v1/admin/cars/{car_id}';
};

export type adminAdminUpdateCarErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminAdminUpdateCarError = adminAdminUpdateCarErrors[keyof adminAdminUpdateCarErrors];

export type adminAdminUpdateCarResponses = {
    /**
     * Successful Response
     */
    200: CarPublic;
};

export type adminAdminUpdateCarResponse = adminAdminUpdateCarResponses[keyof adminAdminUpdateCarResponses];

export type adminAdminUploadCarImagesData = {
    body: Body_admin_admin_upload_car_images;
    path: {
        /**
         * Car Id
         */
        car_id: string;
    };
    query?: never;
    url: '/api/v1/admin/cars/{car_id}/images';
};

export type adminAdminUploadCarImagesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminAdminUploadCarImagesError = adminAdminUploadCarImagesErrors[keyof adminAdminUploadCarImagesErrors];

export type adminAdminUploadCarImagesResponses = {
    /**
     * Response Admin-Admin Upload Car Images
     *
     * Successful Response
     */
    200: Array<CarImagePublic>;
};

export type adminAdminUploadCarImagesResponse = adminAdminUploadCarImagesResponses[keyof adminAdminUploadCarImagesResponses];

export type adminAdminDeleteCarImageData = {
    body?: never;
    path: {
        /**
         * Car Id
         */
        car_id: string;
        /**
         * Image Id
         */
        image_id: string;
    };
    query?: never;
    url: '/api/v1/admin/cars/{car_id}/images/{image_id}';
};

export type adminAdminDeleteCarImageErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminAdminDeleteCarImageError = adminAdminDeleteCarImageErrors[keyof adminAdminDeleteCarImageErrors];

export type adminAdminDeleteCarImageResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type adminAdminDeleteCarImageResponse = adminAdminDeleteCarImageResponses[keyof adminAdminDeleteCarImageResponses];

export type adminAdminUpdateCarImageData = {
    body?: never;
    path: {
        /**
         * Car Id
         */
        car_id: string;
        /**
         * Image Id
         */
        image_id: string;
    };
    query?: {
        /**
         * Is Primary
         */
        is_primary?: boolean | null;
        /**
         * Display Order
         */
        display_order?: number | null;
    };
    url: '/api/v1/admin/cars/{car_id}/images/{image_id}';
};

export type adminAdminUpdateCarImageErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminAdminUpdateCarImageError = adminAdminUpdateCarImageErrors[keyof adminAdminUpdateCarImageErrors];

export type adminAdminUpdateCarImageResponses = {
    /**
     * Successful Response
     */
    200: CarImagePublic;
};

export type adminAdminUpdateCarImageResponse = adminAdminUpdateCarImageResponses[keyof adminAdminUpdateCarImageResponses];

export type adminAdminReorderCarImagesData = {
    body: CarImageReorder;
    path: {
        /**
         * Car Id
         */
        car_id: string;
    };
    query?: never;
    url: '/api/v1/admin/cars/{car_id}/images/reorder';
};

export type adminAdminReorderCarImagesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminAdminReorderCarImagesError = adminAdminReorderCarImagesErrors[keyof adminAdminReorderCarImagesErrors];

export type adminAdminReorderCarImagesResponses = {
    /**
     * Response Admin-Admin Reorder Car Images
     *
     * Successful Response
     */
    200: Array<CarImagePublic>;
};

export type adminAdminReorderCarImagesResponse = adminAdminReorderCarImagesResponses[keyof adminAdminReorderCarImagesResponses];

export type adminReadSiteSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/site-settings';
};

export type adminReadSiteSettingsResponses = {
    /**
     * Successful Response
     */
    200: SiteSettingsPublic;
};

export type adminReadSiteSettingsResponse = adminReadSiteSettingsResponses[keyof adminReadSiteSettingsResponses];

export type adminUpdateSiteSettingsData = {
    body: SiteSettingsUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/admin/site-settings';
};

export type adminUpdateSiteSettingsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminUpdateSiteSettingsError = adminUpdateSiteSettingsErrors[keyof adminUpdateSiteSettingsErrors];

export type adminUpdateSiteSettingsResponses = {
    /**
     * Successful Response
     */
    200: SiteSettingsPublic;
};

export type adminUpdateSiteSettingsResponse = adminUpdateSiteSettingsResponses[keyof adminUpdateSiteSettingsResponses];

export type adminReadInquiriesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Is Read
         */
        is_read?: boolean | null;
        /**
         * Car Id
         */
        car_id?: string | null;
        /**
         * Search
         */
        search?: string | null;
    };
    url: '/api/v1/admin/inquiries/';
};

export type adminReadInquiriesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminReadInquiriesError = adminReadInquiriesErrors[keyof adminReadInquiriesErrors];

export type adminReadInquiriesResponses = {
    /**
     * Successful Response
     */
    200: CarInquiriesPublic;
};

export type adminReadInquiriesResponse = adminReadInquiriesResponses[keyof adminReadInquiriesResponses];

export type adminAdminDeleteInquiryData = {
    body?: never;
    path: {
        /**
         * Inquiry Id
         */
        inquiry_id: string;
    };
    query?: never;
    url: '/api/v1/admin/inquiries/{inquiry_id}';
};

export type adminAdminDeleteInquiryErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminAdminDeleteInquiryError = adminAdminDeleteInquiryErrors[keyof adminAdminDeleteInquiryErrors];

export type adminAdminDeleteInquiryResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type adminAdminDeleteInquiryResponse = adminAdminDeleteInquiryResponses[keyof adminAdminDeleteInquiryResponses];

export type adminAdminUpdateInquiryData = {
    body: CarInquiryUpdate;
    path: {
        /**
         * Inquiry Id
         */
        inquiry_id: string;
    };
    query?: never;
    url: '/api/v1/admin/inquiries/{inquiry_id}';
};

export type adminAdminUpdateInquiryErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type adminAdminUpdateInquiryError = adminAdminUpdateInquiryErrors[keyof adminAdminUpdateInquiryErrors];

export type adminAdminUpdateInquiryResponses = {
    /**
     * Successful Response
     */
    200: CarInquiryPublic;
};

export type adminAdminUpdateInquiryResponse = adminAdminUpdateInquiryResponses[keyof adminAdminUpdateInquiryResponses];

export type adminReadAdminStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/stats/';
};

export type adminReadAdminStatsResponses = {
    /**
     * Successful Response
     */
    200: AdminStatsPublic;
};

export type adminReadAdminStatsResponse = adminReadAdminStatsResponses[keyof adminReadAdminStatsResponses];

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];
