"""add cars, car images and site settings

Revision ID: 36f593fef00b
Revises: fe56fa70289e
Create Date: 2026-09-30 14:02:16.609229

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '36f593fef00b'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sitesettings',
    sa.Column('dealership_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('hero_headline', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('hero_subheadline', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('hero_image_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('hero_video_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_phone', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('make', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('engine', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('transmission', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('exterior_color', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('interior_color', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('vin', sqlmodel.sql.sqltypes.AutoString(length=17), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_sold', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carimage',
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('car_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carimage_car_id'), 'carimage', ['car_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carimage_car_id'), table_name='carimage')
    op.drop_table('carimage')
    op.drop_table('car')
    op.drop_table('sitesettings')
    # ### end Alembic commands ###
